x

diff --git a/.github/workflows/_all_ci.yml b/.github/workflows/_all_ci.yml
--- a/.github/workflows/_all_ci.yml
+++ b/.github/workflows/_all_ci.yml
@@ -111,8 +111,16 @@ jobs:
   ci_end:
     name: "CI Success"
     needs: [lint, test, compile-integration-tests, dependencies, extended-tests]
-    if: ${{ !failure() }}
+    if: ${{ always() }}
     runs-on: ubuntu-latest
     steps:
       - name: "CI Success"
-        run: echo "CI end"
+        if: ${{ !failure() }}
+        run: |
+          echo "Success"
+          exit 0
+      - name: "CI Failure"
+        if: ${{ failure() }}
+        run: |
+          echo "Failure"
+          exit 1
